document.addEventListener('DOMContentLoaded', function () {
  const domainSelect = document.getElementById('domainSelect');
  const gameLinksDiv = document.getElementById('gameLinks');

  const games = [  
    { name: "bitlife" },
    { name: "monkey-mart" },
    { name: "stickman-hook" },
    { name: "tunnel-rush" },
    { name: "pvz-2" },
    { name: "slope" },
    { name: "slope-2" },
    { name: "clicker-heroes" },
    { name: "retro-bowl" },
    { name: "subway-surfers", subdomain: "games" },
    { name: "soccer-random" },
    { name: "basket-random" },
    { name: "volley-random" },
    { name: "boxing-random" },
    { name: "superhot" },
    { name: "temple-run-2" },
    { name: "fbwg-1" },
    { name: "fbwg-2" },
    { name: "fbwg-3" },
    { name: "fbwg-4" },
    { name: "fbwg-5" },
    { name: "rooftop-snipers" },
    { name: "rooftop-snipers-2" },
    { name: "duck-life" },
    { name: "duck-life-2" },
    { name: "duck-life-3" },
    { name: "duck-life-4", subdomain: "games"  },
    { name: "duck-life-treasure-hunt", subdomain: "games"  },
    { name: "duck-life-6" },
    { name: "cookie-clicker" },
    { name: "geometry-dash" },
    { name: "tidal-wave", subdomain: "games-cloudflare-2" },
    { name: "friday-night-funkin" },
    { name: "getting-over-it-scratch-edition", subdomain: "games" },
    { name: "flappy-bird" },
    { name: "learn-to-fly" },
    { name: "learn-to-fly-2" },
    { name: "learn-to-fly-3" },
    { name: "learn-to-fly-idle" },
    { name: "moto-x3m" },
    { name: "moto-x3m-2" },
    { name: "moto-x3m-3" },
    { name: "moto-x3m-winter" },
    { name: "moto-x3m-pool-party" },
    { name: "moto-x3m-spooky-land" },
    { name: "boxel-rebound" },
    { name: "doodle-jump" },
    { name: "crossy-road" },
    { name: "little-alchemy", subdomain: "little-alchemy"  },
    { name: "little-alchemy-2", subdomain: "little-alchemy-2"  },
    { name: "doge-miner" },
    { name: "doge-miner-2", subdomain: "games" },
    { name: "bob-the-robber", subdomain: "games-cloudflare-2" },
    { name: "money-movers-3" },
    { name: "bloons-td" },
    { name: "bloons-td-2" },
    { name: "bloons-td-3" },
    { name: "bloons-td-4" },
    { name: "bloons-td-4-expansion-pack" },
    { name: "bloons-td-6" },
    { name: "idle-breakout" },
    { name: "worlds-hardest-game" },
    { name: "worlds-hardest-game-2" },
    { name: "run" },
    { name: "run-2" },
    { name: "jacksmith" },
    { name: "papas-scooperia", subdomain: "games-cloudflare-2" },
    { name: "papas-sushiria", subdomain: "games-cloudflare-2" },
    { name: "papas-cupcakeria", subdomain: "games-cloudflare-2" },
    { name: "papas-bakeria", subdomain: "games-cloudflare-2" },
    { name: "papas-burgeria", subdomain: "games-cloudflare-2" },
    { name: "papas-cheeseria", subdomain: "games-cloudflare-2" },
    { name: "papas-pastaria", subdomain: "games-cloudflare-2" },
    { name: "papas-hot-doggeria", subdomain: "games-cloudflare-2" },
    { name: "papas-panckaeria", subdomain: "games-cloudflare-2" },
    { name: "papas-donuteria", subdomain: "games-cloudflare-2" },
    { name: "papas-pizzeria", subdomain: "games-cloudflare-2" },
    { name: "papas-freezeria", subdomain: "games-cloudflare-2" },
    { name: "papas-taco-mia", subdomain: "games-cloudflare-2" },
    { name: "papas-wingeria", subdomain: "games-cloudflare-2" },
    { name: "papa-louie", subdomain: "games-cloudflare-2" },
    { name: "papa-louie-2" },
    { name: "papa-louie-3" },
    { name: "colour-switch" },
    { name: "colour-switch-2-challenges" },
    { name: "bad-ice-cream-2" },
    { name: "bad-ice-cream-3" },
    { name: "fruit-ninja" },
    { name: "vex-3" },
    { name: "vex-4" },
    { name: "vex-5" },
    { name: "vex-6" },
    { name: "vex-7" },
    { name: "house-of-hazards" },
    { name: "2048" },
    { name: "flappy-2048" },
    { name: "doge-2048" },
    { name: "1" },
    { name: "9007199254" },
    { name: "core-ball" },
    { name: "bloxors" },
    { name: "elastic-man" },
    { name: "you-are-bezos" },
    { name: "cars-simulator", subdomain: "games" },
    { name: "madalin-stunt-cars-2", subdomain: "games" },
    { name: "madalin-stunt-cars-3", subdomain: "games" },
    { name: "eggy-car" },
    { name: "draw-the-hill" },
    { name: "ball-blast" },
    { name: "big-red-button" },
    { name: "rolly-vortex" },
    { name: "paper-io-2" },
    { name: "just-one-boss" },
    { name: "uno-online" },
    { name: "cluster-rush" },
    { name: "tube-jumpers" },
    { name: "osu" },
    { name: "getaway-shootout" },
    { name: "breaking-the-bank" },
    { name: "stack" },
    { name: "tetris" },
    { name: "2020-game" },
    { name: "achievement-unlocked" },
    { name: "achievement-unlocked-2" },
    { name: "achievement-unlocked-3" },
    { name: "adam-and-eve" },
    { name: "adam-and-eve-2" },
    { name: "adam-and-eve-3" },
    { name: "mini-stilts" },
    { name: "green" },
    { name: "dodge" },
    { name: "city-blocks-2" },
    { name: "anti-terrorist-rush" },
    { name: "awesome-tanks" },
    { name: "awesome-tanks-2" },
    { name: "bacon-may-die" },
    { name: "3d-missile" },
    { name: "gun-blood" },
    { name: "apple-shooter" },
    { name: "bow-man" },
    { name: "bow-man-2" },
    { name: "kitchen-gun-game" },
    { name: "kitten-cannon" },
    { name: "bad-time-simulator" },
    { name: "gimme-the-airpod" },
    { name: "gun-mayhem" },
    { name: "gun-mayhem-2" },
    { name: "gun-mayhem-3" },
    { name: "age-of-war" },
    { name: "age-of-war-2" },
    { name: "protektor" },
    { name: "tactical-weapon-pack-2" },
    { name: "arcade-wizard" },
    { name: "push-the-square" },
    { name: "push-your-luck" },
    { name: "rise-of-the-neon-square" },
    { name: "short-ride" },
    { name: "99-balls-evo" },
    { name: "gravity-soccer" },
    { name: "generic-fishing-game" },
    { name: "cannon-basketball-4" },
    { name: "backflip-dive-3d" },
    { name: "basket-bros-io" },
    { name: "basketball-legends" },
    { name: "basketball-stars" },
    { name: "basket-and-ball" },
    { name: "basketball-io" },
    { name: "aspiring-artist" },
    { name: "blocky-snakes" },
    { name: "death-soul" },
    { name: "duke-dashington-remastered" },
    { name: "factory-balls-forever" },
    { name: "flappy-defense" },
    { name: "geo-dash-2" },
    { name: "geometry-jump-sketchy" },
    { name: "klocki" },
    { name: "linquest" },
    { name: "kart-fight-io" },
    { name: "clean-up-io" },
    { name: "one-screen-run" },
    { name: "one-screen-run-2" },
    { name: "evil-glitch" },
    { name: "fake-virus" },
    { name: "fancy-pants-adventures" },
    { name: "flippy-fish" },
    { name: "froggys-battle" },
    { name: "game-inside-a-game" },
    { name: "hacker-typer" },
    { name: "george-and-the-printer" },
    { name: "super-mario-bros" },
    { name: "burning-man-2" },
    { name: "grey-box-testing" },
    { name: "grindcraft" },
    { name: "rolling-forests" },
    { name: "minesweeper" },
    { name: "100-player-pong" },
    { name: "rocking-sky-trip" },
    { name: "1-on-1-soccer" },
    { name: "n-gon" },
    { name: "chrome-dino" },
    { name: "frying-nemo" },
    { name: "raft-wars" },
    { name: "airport-madness-3" },
    { name: "60-second-burger-run" },
    { name: "12-mini-battles" },
    { name: "sonic-the-hedgehog" },
    { name: "fnaf" },
    { name: "fnaf-2" },
    { name: "fnaf-3" },
    { name: "fnaf-4" },
    { name: "pizzeria-simulator", subdomain: "games"  },
    { name: "hobo-1" },
    { name: "hobo-2" },
    { name: "hobo-3" },
    { name: "hobo-4" },
    { name: "hobo-5" },
    { name: "hobo-6" },
    { name: "hobo-7" },
    { name: "qwop" },
    { name: "strike-force-heroes-1", subdomain: "games-cloudflare-2" },
    { name: "strike-force-heroes-2", subdomain: "games-cloudflare-2" },
    { name: "strike-force-heroes-3", subdomain: "games-cloudflare-2" },
    { name: "portal", subdomain: "games-cloudflare-2" },
    { name: "candy-crush", subdomain: "games-cloudflare-2" },
    { name: "riddle-school-1", subdomain: "games-cloudflare-2" },
    { name: "riddle-school-2", subdomain: "games-cloudflare-2" },
    { name: "riddle-school-3", subdomain: "games-cloudflare-2" },
    { name: "riddle-school-4", subdomain: "games-cloudflare-2" },
    { name: "riddle-school-5", subdomain: "games-cloudflare-2" },
    { name: "riddle-transfer-1", subdomain: "games-cloudflare-2" },
    { name: "riddle-transfer-2", subdomain: "games-cloudflare-2" },
    { name: "super-fighters", subdomain: "games-cloudflare-2" },
    { name: "rebuild-1", subdomain: "games-cloudflare-2" },
    { name: "rebuild-2", subdomain: "games-cloudflare-2" },
    { name: "diggy", subdomain: "games-cloudflare-2" },
    { name: "penguin-diner", subdomain: "games-cloudflare-2" },
    { name: "effing-worms-1", subdomain: "games-cloudflare-2" },
    { name: "effing-worms-2", subdomain: "games-cloudflare-2" },
    { name: "effing-worms-xmas", subdomain: "games-cloudflare-2" },
    { name: "wheely-1", subdomain: "games-cloudflare-2" },
    { name: "wheely-2", subdomain: "games-cloudflare-2" },
    { name: "wheely-3", subdomain: "games-cloudflare-2" },
    { name: "wheely-4", subdomain: "games-cloudflare-2" },
    { name: "wheely-5", subdomain: "games-cloudflare-2" },
    { name: "wheely-6", subdomain: "games-cloudflare-2" },
    { name: "wheely-7", subdomain: "games-cloudflare-2" },
    { name: "wheely-8", subdomain: "games-cloudflare-2" },
    { name: "fortz", subdomain: "games-cloudflare-2" },
    { name: "last-stand-union-city", subdomain: "games-cloudflare-2" },
    { name: "my-friend-pedro", subdomain: "games-cloudflare-2" },
    { name: "shopping-street", subdomain: "games-cloudflare-2" },
    { name: "shopping-city", subdomain: "games-cloudflare-2" },
    { name: "earn-to-die-1", subdomain: "games-cloudflare-2" },
    { name: "earn-to-die-2", subdomain: "games-cloudflare-2" },
    { name: "earn-to-die-2012", subdomain: "games-cloudflare-2" },
    { name: "alxemy", subdomain: "games-cloudflare-2" },
    { name: "big-shot-boxing", subdomain: "games-cloudflare-2" },
    { name: "granny" },
    { name: "craftmine" },
    { name: "tiny-fishing" },
    { name: "tanuki-sunset", subdomain: "games"  },
    { name: "adofai" },
    { name: "binding-of-isaac" },
    { name: "time-shooter-2" },
    { name: "time-shooter-3" },
    { name: "minecraft", subdomain: "games"  },
    { name: "minecraft-classic", subdomain: "games-cloudflare-2" },
    { name: "sm64" },
    { name: "canyon-defense" },
    { name: "alien-invaders-io" },
    { name: "wordle" },
    { name: "jellydad-hero", subdomain: "games-cloudflare-2" },
    { name: "haunt-the-house", subdomain: "games-cloudflare-2" },
    { name: "dig-to-china" },
    { name: "dumb-ways-to-die-htf-edition" },
    { name: "another-gentlemans-adventure" },
    { name: "mini-mall-millionaire" },
    { name: "jetpack-joyride" },
    { name: "helix-jump" },
    { name: "hexgl" },
    { name: "cut-the-rope" },
    { name: "bad-piggies", subdomain: "games-cloudflare-2" },
    { name: "burrito-bison" },
    { name: "cell-machine" },
    { name: "fluid-simulator" },
    { name: "adventure-capitalist" },
    { name: "chibi-knight", subdomain: "games-cloudflare-2" },
    { name: "champion-island" },
    { name: "circloo" },
    { name: "trap-the-cat", subdomain: "games-cloudflare-2" },
    { name: "adrenaline-challenge", subdomain: "games-cloudflare-2" },
    { name: "avalanche", subdomain: "games-cloudflare-2" },
    { name: "backrooms", subdomain: "games"  },
    { name: "battle-for-gondor", subdomain: "games-cloudflare-2" },
    { name: "the-black-knight", subdomain: "games-cloudflare-2" },
    { name: "boxhead2play", subdomain: "games-cloudflare-2" },
    { name: "champion-archer", subdomain: "games-cloudflare-2" },
    { name: "connect-3" },
    { name: "creative-kill-chamber", subdomain: "games-cloudflare-2" },
    { name: "csgo-clicker" },
    { name: "cubefield", subdomain: "games-cloudflare-2" },
    { name: "johnny-upgrade" },
    { name: "jelly-truck" },
    { name: "one-more-flight", subdomain: "games-cloudflare-2" },
  ];

  function generatePathFromName(name) {
    return name.replace(/\s+/g, '-').toLowerCase();
  }

  function updateGameLinks(domain) {
    gameLinksDiv.innerHTML = ''; // Clear existing links

    games.forEach(game => {
      const link = document.createElement('a');
      const subdomain = game.subdomain || "games-cloudflare";
      const path = generatePathFromName(game.name);
      const url = `https://${subdomain}.${domain}/${path}/`;
      link.href = url;
      link.textContent = game.name;
      link.target = "_blank";
      gameLinksDiv.appendChild(link);
      gameLinksDiv.appendChild(document.createElement('br'));
    });
  }

  domainSelect.addEventListener('change', function () {
    updateGameLinks(this.value);
  });

  updateGameLinks(domainSelect.value);
});
